workflows:
  xamarin-android:
    name: Xamarin Android Build
    instance_type: mac_mini_m1 # Χρησιμοποιούμε macOS για καλύτερη υποστήριξη Xamarin
    max_build_duration: 120 # Διάρκεια build σε λεπτά
    environment:
      vars:
        PROJECT_PATH: "YourSolutionName.sln" # Αντικατάστησε το με το όνομα του .sln αρχείου σου
        CONFIGURATION: "Release" # Μπορεί να είναι Debug ή Release
        ANDROID_PROJECT_PATH: "YourAndroidProject.csproj" # Το μονοπάτι του Android project
      node: latest # Για διαχείριση npm αν χρειάζεται
      xcode: latest # Εγκατάσταση Xcode για Mac builds αν χρειάζεται
    scripts:
      - name: Εγκατάσταση του .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version latest
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --version
      
      - name: Επαναφορά των NuGet packages
        script: |
          nuget restore $PROJECT_PATH
          dotnet restore $PROJECT_PATH

      - name: Build του Xamarin Android project
        script: |
          msbuild $ANDROID_PROJECT_PATH /t:Rebuild /p:Configuration=$CONFIGURATION /p:Platform="Any CPU"

      - name: Εύρεση και αποθήκευση του APK
        script: |
          find . -name "*.apk" -exec mv {} $CM_BUILD_DIR/output.apk \;
    
    artifacts:
      - output.apk
