workflows:
  xamarin-android:
    name: Xamarin Android Build
    instance_type: mac_mini_m1
    environment:
      vars:
        CONFIGURATION: "Release"
        ANDROID_PROJECT_PATH: "MyProject.csproj"
      node: latest
      xcode: latest
    scripts:
      - name: Εγκατάσταση του .NET SDK και Xamarin
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version latest
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --version
          dotnet nuget locals all --clear
      - name: Restore NuGet packages
        script: |
          dotnet restore $ANDROID_PROJECT_PATH
      - name: Build Xamarin Android project
        script: |
          dotnet build $ANDROID_PROJECT_PATH --configuration $CONFIGURATION
      - name: Find and save the APK
        script: |
          find . -name "*.apk" -exec mv {} $CM_BUILD_DIR/output.apk \;
    artifacts:
      - output.apk
