workflows:
  xamarin-android:
    name: Xamarin Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PROJECT_PATH: "YourSolutionName.sln" # Αντικατάστησε με το δικό σου .sln αρχείο
        CONFIGURATION: "Release"
        ANDROID_PROJECT_PATH: "YourAndroidProject.csproj"
      node: latest
      xcode: latest
    scripts:
      - name: Εγκατάσταση του .NET SDK και NuGet
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version latest
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --version
          dotnet nuget locals all --clear
      
      - name: Αναβάθμιση NuGet και επαναφορά των πακέτων
        script: |
          mono /Library/Frameworks/Mono.framework/Versions/Current/bin/nuget update -self
          mono /Library/Frameworks/Mono.framework/Versions/Current/bin/nuget restore $PROJECT_PATH
          dotnet restore $PROJECT_PATH --force

      - name: Build του Xamarin Android project
        script: |
          msbuild $ANDROID_PROJECT_PATH /t:Rebuild /p:Configuration=$CONFIGURATION /p:Platform="Any CPU"

      - name: Εύρεση και αποθήκευση του APK
        script: |
          find . -name "*.apk" -exec mv {} $CM_BUILD_DIR/output.apk \;
    
    artifacts:
      - output.apk
